<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
'About Us'=> '私達について',
 'Advantage'=> '利点',
 'All Manufacturers'=> '全メーカー',
 'Applications'=> 'アプリケーション',
 'Barum Electronics Co., LTD'=> 'Barum電子株式会社',
 'Click to learn more'=> 'より多くを学ぶためにクリック',
 'Company Events'=> '会社のイベント',
 'Contact Us'=> 'お問い合わせ',
 'Culture'=> '文化',
 'Customers'=> 'お客さま',
 'Direction'=> '方向',
 'Distribution Brands'=> 'ディストリビューションブランド',
 'Feature'=> 'フィーチャー',
 'Help'=> '助け',
 'Home'=> 'ホーム',
 'Manufacturer'=> 'メーカー',
 'Manufacturers'=> 'メーカー',
 'Model'=> 'モデル',
 'New Technologies'=> '新技術',
 'Online Inquiry'=> 'オンラインお問い合わせ',
 'Order Tracking'=> '商品追跡',
 'Ordering Information'=> '発注情報',
 'Package'=> 'パッケージ',
 'Popular Searches'=> '人気の検索ワード',
 'Price based on quantity, market conditions and other factors vary. Please call or send a quick inquiry ... Thanks!'=> '量に基づいて価格は、市場の状況やその他の要因は様々である。迅速な問い合わせを呼び出すか、送信してください...ありがとう！',
 'Product Details'=> '商品の詳細',
 'Products'=> '製品',
 'Products Show'=> '製品ショー',
 'Quality Control'=> '品質管理',
 'Quantity'=> '数量',
 'Questions? Please consult our sales'=> '質問？弊社営業にご相談ください',
 'Service'=> 'サービス',
 'Technology'=> 'テクノロジー',
 'Tips: Please fill in the following information to facilitate contact!'=> 'ヒント：連絡先を容易にするために、以下の情報を入力してください！',
 );
