<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Rm. 1005, Block B,Zhonghangbeiyuan Building,Zhonghang Rd.,Futian District,Shenzhen,Guangdong,China' => '',
  'Add: Rm. 1005, Block B,Zhonghangbeiyuan Building,Zhonghang Rd.,Futian District,Shenzhen,Guangdong,China' => '@@追加：Rmの。 1005、Bブロック、Zhonghangbeiyuanビル、Zhonghang路、福田区、深セン、広東省、中国@@',
  'Mark is required, please fill out accurate。' => '@@マークが必要となり、正確にご記入ください。@@',
  'Sales' => '@@販売の@@',
  'Add' => '加える',
  'All' => 'すべて',
  'Any question? Please consult our technical staff and customer service personnel!' => 'どんな質問？当社の技術スタッフと顧客サービス担当者にご相談ください！',
  'Barum Electronics Co., LTD had been established， in line with the good faith principle, is supreme, the mutually beneficial reciprocal benefit management ' => 'Barum電子有限公司が設立されていた、誠実の原則に沿ったもので、最高裁で、相互に有益な相互の利益管理',
  'Brand agency' => 'ブランドの代理店',
  'Captcha' => 'キャプチャ',
  'Change Pic' => 'チェンジピック',
  'Classify' => '分類する',
  'Click for Pic' => 'ピックはここをクリック',
  'Company' => '会社',
  'Contact' => '連絡',
  'Contact Us' => 'お問い合わせ',
  'Content' => 'コンテンツ',
  'Create Date' => '日付を作成します。',
  'Customer Service' => '顧客サービス',
  'Delete' => '削除',
  'Direction' => '方向',
  'Fast delivery' => '高速配信',
  'Fax' => 'ファックス',
  'Headline' => 'ヘッドライン',
  'Honesty' => '正直',
  'Index' => 'インデックス',
  'Keyword' => 'キーワード',
  'Large inventory spot' => '大規模な在庫スポット',
  'Manufacturer' => 'メーカー',
  'Mark is required, please fill out accurate' => 'マークが必要となり、正確にご記入ください',
  'Model' => 'モデル',
  'More than 500 global components brands channels of supply and distributed components of the United States, Europe, Asia these brand manufacturers, including integrated circuits, two transistors, resistors and capacitors, connectors, modules, etc.' => '500以上のグローバルな部品供給や米国、ヨーロッパ、アジアの分散コンポーネントのチャンネルをブランドなどの集積回路、2のトランジスタ、抵抗、コンデンサ、コネクタ、モジュール、など、これらのブランドメーカー、',
  'Online Inquiry' => 'オンラインお問い合わせ',
  'Package' => 'パッケージ',
  'Please enter the quantity you need. If you have more than one component are looking for, please add additional components to your quote request form. Then fill in your contact information and click on submit an application, our sales representative will contact you as soon as possible, including price and delivery time. If you need help, please send an E-MAIL to info@barum-hk.com' => '必要な数量を入力してください。あなたが一度に複数のコンポーネントを探している持っている場合は、見積もり依頼フォームにコンポーネントを追加してください。次に、あなたの連絡先情報を記入し、申請書を提出をクリックして当社の営業担当者は、価格·納期を含め、可能な限り早くご連絡させていただきます。ヘルプが必要な場合は、info@barum-hk.comに電子メールを送ってください',
  'Please select a manufacturers:' => 'メーカーを選択してください。',
  'Please select a product classify:' => '製品の分類を選択してください。',
  'Price' => '価格',
  'Product List' => '製品一覧',
  'Provide one-stop service' => 'ワンストップサービスを提供',
  'Quantity' => '数量',
  'Quick Quote, quality' => 'クイック見積もり、品質',
  'Reliable' => '信頼できる',
  'Search' => '検索',
  'Search Model:' => 'サーチモデル：',
  'Specialty' => '専門',
  'Submit' => '提出する',
  'Technical Support' => 'テクニカルサポート',
  'Tel' => '電話番号',
  'Telephone' => '電話',
  'View map' => '地図を見る',
  'Welcome to Barum Electronics' => 'Barumエレクトロニクスへようこそ',
  'Why Barum?' => 'なぜBarum？',
);
