<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '63eu.com' => '',
  'Contact Person' => '',
  'Incorrect verification code' => '',
  'SendRFQ' => '',
  'Website Technology Support' => '',
  'About Us' => 'من نحن',
  'Advantage' => 'ميزة',
  'All Manufacturers' => 'كل الماركات',
  'Applications' => 'تطبيقات',
  'Barum Electronics Co., LTD' => 'باروم إلكترونيات المحدودة',
  'Click to learn more' => 'انقر لمعرفة المزيد',
  'Company Events' => 'الشركة الأحداث',
  'Contact Us' => 'الاتصال بنا',
  'Culture' => 'ثقافة',
  'Customers' => 'الزبائن',
  'Direction' => 'اتجاه',
  'Distribution Brands' => 'العلامات التجارية التوزيع',
  'Feature' => 'ميزة',
  'Help' => 'مساعدة',
  'Home' => 'منزل',
  'Manufacturer' => 'الشركة المصنعة',
  'Manufacturers' => 'مصنعين',
  'Model' => 'نموذج',
  'New Technologies' => 'تقنيات جديدة',
  'Online Inquiry' => 'رسالتك على الانترنت',
  'Order Tracking' => 'تتبع النظام',
  'Ordering Information' => 'معلومات يأمر',
  'Package' => 'صفقة',
  'Popular Searches' => 'بحث شعبية',
  'Price based on quantity, market conditions and other factors vary. Please call or send a quick inquiry ... Thanks!' => 'السعر على أساس الكمية، وظروف السوق وعوامل أخرى تختلف. يرجى الاتصال أو إرسال استفسار سريع ... شكرا!',
  'Product Details' => 'تفاصيل المنتج',
  'Products' => 'المنتجات',
  'Products Show' => 'المنتجات مشاهدة',
  'Quality Control' => 'ضبط الجودة',
  'Quantity' => 'كمية',
  'Questions? Please consult our sales' => 'الأسئلة؟ يرجى الرجوع إلى المبيعات لدينا',
  'Service' => 'خدمة',
  'Technology' => 'تكنولوجيا',
  'Tips: Please fill in the following information to facilitate contact!' => 'نصائح: يرجى تعبئة المعلومات التالية لتسهيل الاتصال!',
);
