<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
'Add'=> 'إضافة',
 'Delete'=> 'حذف',
 'Manufacturer'=> 'الشركة المصنعة',
 'Mark is required, please fill out accurate'=> 'مطلوب علامة، يرجى ملء دقيقة',
 'Please enter the quantity you need. If you have more than one component are looking for, please add additional components to your quote request form. Then fill in your contact information and click on submit an application, our sales representative will contact you as soon as possible, including price and delivery time. If you need help, please send an E-MAIL to sales@Barum.com'=> 'يرجى إدخال الكمية التي تحتاج إليها. إذا كان لديك يبحثون أكثر من عنصر واحد ل، يرجى إضافة مكونات إضافية إلى نموذج طلب أقتبس الخاصة بك. ثم ملء معلومات الاتصال الخاصة بك وانقر على تقديم طلب، ومندوب مبيعات لدينا نتصل بك في أقرب وقت ممكن، بما في ذلك السعر ووقت التسليم. إذا كنت بحاجة إلى مساعدة، يرجى إرسال رسالة بالبريد الإلكتروني إلى sales@Barum.com',
 'Submit'=> 'عرض',
 'Mark is required, please fill out accurate。'=> 'مطلوب علامة، يرجى ملء دقيقة.',
 'Add: Rm. 1005, Block B,Zhonghangbeiyuan Building,Zhonghang Rd.,Futian District,Shenzhen,Guangdong,China'=> 'إضافة: رينغيت ماليزي. 1005، بلوك ب، مبنى Zhonghangbeiyuan، طريق Zhonghang.، مقاطعة الرقمين، شنتشن، قوانغدونغ، والصين',
 'All'=> 'كل',
 'Any question? Please consult our technical staff and customer service personnel!'=> 'أي سؤال؟ يرجى استشارة موظفينا التقنية وموظفي خدمة العملاء!',
 'Barum Electronics Co., LTD had been established， in line with the good faith principle, is supreme, the mutually beneficial reciprocal benefit management '=> 'وكان باروم إلكترونيات المحدودة أنشئت، وذلك تمشيا مع مبدأ حسن النية، هي العليا، والمنفعة المتبادلة المنفعة المتبادلة الإدارة',
 'Brand agency'=> 'وكالة العلامة التجارية',
 'Captcha'=> 'CAPTCHA',
 'Change Pic'=> 'تغيير صورة',
 'Classify'=> 'صنف',
 'Click for Pic'=> 'انقر لبيك',
 'Company'=> 'شركة',
 'Contact'=> 'اتصال',
 'Contact Us'=> 'الاتصال بنا',
 'Content'=> 'محتوى',
 'Create Date'=> 'إنشاء التسجيل',
 'Customer Service'=> 'خدمة العملاء',
 'Direction'=> 'اتجاه',
 'Fast delivery'=> 'تسليم سريع',
 'Fax'=> 'الفاكس',
 'Headline'=> 'عنوان رئيسي',
 'Honesty'=> 'أمانة',
 'Index'=> 'مؤشر',
 'Keyword'=> 'الكلمة',
 'Large inventory spot'=> 'بقعة مخزون كبير',
 'Model'=> 'نموذج',
 'More than 500 global components brands channels of supply and distributed components of the United States, Europe, Asia these brand manufacturers, including integrated circuits, two transistors, resistors and capacitors, connectors, modules, etc.'=> 'أكثر من 500 مكونات ماركات عالمية قنوات العرض ومكونات وزعت الولايات المتحدة وأوروبا وآسيا هذه الشركات المصنعة العلامة التجارية، بما في ذلك الدوائر المتكاملة، واثنين من الترانزستورات، المقاومات والمكثفات، والموصلات، وحدات، الخ',
 'Online Inquiry'=> 'رسالتك على الانترنت',
 'Package'=> 'صفقة',
 'Please select a manufacturers:'=> 'يرجى تحديد الشركات المصنعة:',
 'Please select a product classify:'=> 'يرجى تحديد يصنف المنتج:',
 'Price'=> 'السعر',
 'Product List'=> 'قائمة المنتجات',
 'Provide one-stop service'=> 'توفير خدمة الشباك الواحد',
 'Quantity'=> 'كمية',
 'Quick Quote, quality'=> 'اقتباس سريعة ونوعية',
 'Reliable'=> 'موثوق',
 'Sales'=> 'مبيعات',
 'Search'=> 'بحث',
 'Search Model:'=> 'بحث موديل:',
 'Specialty'=> 'تخصص',
 'Technical Support'=> 'الدعم الفني',
 'Tel'=> 'الهاتف',
 'Telephone'=> 'هاتف',
 'View map'=> 'عرض خريطة',
 'Welcome to Barum Electronics'=> 'مرحبا بكم في باروم إلكترونيات',
 'Why Barum?'=> 'لماذا باروم؟',
 );
