<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '63eu.com' => '',
  'Contact Person' => '',
  'Incorrect verification code' => '',
  'SendRFQ' => '',
  'Website Technology Support' => '',
  'About Us' => 'About Us',
  'Advantage' => 'Advantage',
  'All Manufacturers' => 'All Manufacturers',
  'Applications' => 'Applications',
  'Barum Electronics Co., LTD' => 'Barum Electronics Co., LTD',
  'Click to learn more' => 'Click to learn more',
  'Company Events' => 'Company Events',
  'Contact Us' => 'Contact Us',
  'Culture' => 'Culture',
  'Customers' => 'Customers',
  'Direction' => 'Direction',
  'Distribution Brands' => 'Distribution Brands',
  'Feature' => 'Feature',
  'Help' => 'Help',
  'Home' => 'Home',
  'Manufacturer' => 'Manufacturer',
  'Manufacturers' => 'Manufacturers',
  'Model' => 'Model',
  'New Technologies' => 'New Technologies',
  'Online Inquiry' => 'Online Inquiry',
  'Order Tracking' => 'Order Tracking',
  'Ordering Information' => 'Ordering Information',
  'Package' => 'Package',
  'Popular Searches' => 'Popular Searches',
  'Price based on quantity, market conditions and other factors vary. Please call or send a quick inquiry ... Thanks!' => 'Price based on quantity, market conditions and other factors vary. Please call or send a quick inquiry ... Thanks!',
  'Product Details' => 'Product Details',
  'Products' => 'Products',
  'Products Show' => 'Products Show',
  'Quality Control' => 'Quality Control',
  'Quantity' => 'Quantity',
  'Questions? Please consult our sales' => 'Questions? Please consult our sales',
  'Service' => 'Service',
  'Technology' => 'Technology',
  'Tips: Please fill in the following information to facilitate contact!' => 'Tips: Please fill in the following information to facilitate contact!',
);
