<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
'About Us'=> 'Über uns',
 'Advantage'=> 'Vorteil',
 'All Manufacturers'=> 'Alle Hersteller',
 'Applications'=> 'Anwendungen',
 'Barum Electronics Co., LTD'=> 'Barum Electronics Co., LTD',
 'Click to learn more'=> 'Klicken Sie hier um mehr zu erfahren',
 'Company Events'=> 'Unternehmen Veranstaltungen',
 'Contact Us'=> 'Kontaktieren Sie uns',
 'Culture'=> 'Kultur',
 'Customers'=> 'Kundschaft',
 'Direction'=> 'Richtung',
 'Distribution Brands'=> 'Verteilung Marken',
 'Feature'=> 'Feature',
 'Help'=> 'Hilfe',
 'Home'=> 'Zuhause',
 'Manufacturer'=> 'Hersteller',
 'Manufacturers'=> 'Hersteller',
 'Model'=> 'Modell',
 'New Technologies'=> 'Neue Technologien',
 'Online Inquiry'=> 'Online-Anfrage',
 'Order Tracking'=> 'Bestellstatus',
 'Ordering Information'=> 'Bestellinformationen',
 'Package'=> 'Paket',
 'Popular Searches'=> 'Beliebte Suchen',
 'Price based on quantity, market conditions and other factors vary. Please call or send a quick inquiry ... Thanks!'=> 'Preis basierend auf Menge, Marktbedingungen und anderen Faktoren variieren. Bitte rufen Sie an oder senden Sie eine kurze Anfrage ... Vielen Dank!',
 'Product Details'=> 'Produktdetails',
 'Products'=> 'Produkte',
 'Products Show'=> 'Produkte anzeigen',
 'Quality Control'=> 'Qualitätskontrolle',
 'Quantity'=> 'Menge',
 'Questions? Please consult our sales'=> 'Fragen? Bitte konsultieren Sie unsere Verkaufs',
 'Service'=> 'Service',
 'Technology'=> 'Technologie',
 'Tips: Please fill in the following information to facilitate contact!'=> 'Tipps: Füllen Sie bitte die folgenden Informationen, um Kontakt zu erleichtern!',
 );
