<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
'Add'=> 'Hinzufügen',
 'Delete'=> 'Löschen',
 'Manufacturer'=> 'Hersteller',
 'Mark is required, please fill out accurate'=> 'Mark erforderlich ist, füllen Sie bitte das genaue',
 'Please enter the quantity you need. If you have more than one component are looking for, please add additional components to your quote request form. Then fill in your contact information and click on submit an application, our sales representative will contact you as soon as possible, including price and delivery time. If you need help, please send an E-MAIL to sales@Barum.com'=> 'Bitte geben Sie die Menge, die Sie benötigen. Wenn Sie mehr als eine Komponente suchen, fügen Sie bitte zusätzliche Komponenten, um Ihre Anfrageformular. Dann füllen Sie Ihre Kontaktinformationen und klicken Sie auf einen Antrag, werden unsere Vertriebsmitarbeiter Sie so bald wie möglich kontaktieren, einschließlich Preis und Lieferzeit. Wenn Sie Hilfe benötigen, senden Sie bitte eine E-Mail an sales@Barum.com',
 'Submit'=> 'Einreichen',
 'Mark is required, please fill out accurate。'=> 'Mark ist erforderlich, füllen Sie bitte genau.',
 'Add: Rm. 1005, Block B,Zhonghangbeiyuan Building,Zhonghang Rd.,Futian District,Shenzhen,Guangdong,China'=> 'In: Rm. 1005, Block B, Zhonghangbeiyuan Gebäude, Zhonghang Rd., Futian District, Shenzhen, Guangdong, China',
 'All'=> 'Alle',
 'Any question? Please consult our technical staff and customer service personnel!'=> 'Noch eine Frage? Bitte beachten Sie unsere technischen Mitarbeiter-und Kundendienstpersonal!',
 'Barum Electronics Co., LTD had been established， in line with the good faith principle, is supreme, the mutually beneficial reciprocal benefit management '=> 'Barum Electronics Co., LTD gegründet worden war, im Einklang mit dem Grundsatz Treu und Glauben, ist oberste, die gegenseitig vorteilhaften wechselseitigen Leistungsmanagement',
 'Brand agency'=> 'Markenagentur',
 'Captcha'=> 'Captcha-',
 'Change Pic'=> 'Ändern Pic',
 'Classify'=> 'Klassifizieren',
 'Click for Pic'=> 'Klicken Sie für Pic',
 'Company'=> 'Firma',
 'Contact'=> 'Kontakt',
 'Contact Us'=> 'Kontaktieren Sie uns',
 'Content'=> 'Inhalt',
 'Create Date'=> 'Erstellungsdatum',
 'Customer Service'=> 'Kundenservice',
 'Direction'=> 'Richtung',
 'Fast delivery'=> 'Schnelle Lieferung',
 'Fax'=> 'Fax',
 'Headline'=> 'Überschrift',
 'Honesty'=> 'Ehrlichkeit',
 'Index'=> 'Index',
 'Keyword'=> 'Stichwort',
 'Large inventory spot'=> 'Große Bestandsaufnahme vor Ort',
 'Model'=> 'Modell',
 'More than 500 global components brands channels of supply and distributed components of the United States, Europe, Asia these brand manufacturers, including integrated circuits, two transistors, resistors and capacitors, connectors, modules, etc.'=> 'Mehr als 500 globale Komponenten Marken Versorgungswege und verteilten Komponenten der Vereinigten Staaten, Europa, Asien diese Markenhersteller, darunter integrierte Schaltungen, zwei Transistoren, Widerstände und Kondensatoren, Stecker, Module, etc.',
 'Online Inquiry'=> 'Online-Anfrage',
 'Package'=> 'Paket',
 'Please select a manufacturers:'=> 'Bitte wählen Sie einen Hersteller:',
 'Please select a product classify:'=> 'Bitte wählen Sie ein Produkt klassifizieren:',
 'Price'=> 'Preis',
 'Product List'=> 'Artikelliste',
 'Provide one-stop service'=> 'Bieten Sie Service aus einer Hand',
 'Quantity'=> 'Menge',
 'Quick Quote, quality'=> 'Quick Quote, Qualität',
 'Reliable'=> 'Zuverlässig',
 'Sales'=> 'Vertrieb',
 'Search'=> 'Suche',
 'Search Model:'=> 'Suche nach Modell:',
 'Specialty'=> 'Spezialität',
 'Technical Support'=> 'Technischer Support',
 'Tel'=> 'Tel',
 'Telephone'=> 'Telefon',
 'View map'=> 'Karte anzeigen',
 'Welcome to Barum Electronics'=> 'Willkommen in Barum Electronics',
 'Why Barum?'=> 'Warum Barum?',
 );
