<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '63eu.com' => '',
  'Contact Person' => '',
  'Incorrect verification code' => '',
  'SendRFQ' => '',
  'Website Technology Support' => '',
  'About Us' => 'О нас',
  'Advantage' => 'преимущество',
  'All Manufacturers' => 'Все производители',
  'Applications' => 'применения',
  'Barum Electronics Co., LTD' => 'Barum Электроника, Лтд',
  'Click to learn more' => 'Нажмите, чтобы узнать больше',
  'Company Events' => 'События компании',
  'Contact Us' => 'связаться с нами',
  'Culture' => 'культура',
  'Customers' => 'Клиенты',
  'Direction' => 'направление',
  'Distribution Brands' => 'распределительные Бренды',
  'Feature' => 'особенность',
  'Help' => 'Помогите',
  'Home' => 'домой',
  'Manufacturer' => 'производитель',
  'Manufacturers' => 'Производители',
  'Model' => 'модель',
  'New Technologies' => 'Новые технологии',
  'Online Inquiry' => 'онлайн запрос',
  'Order Tracking' => 'Отслеживание заказа',
  'Ordering Information' => 'Информация для заказа',
  'Package' => 'пакет',
  'Popular Searches' => 'Популярные поисковые запросы',
  'Price based on quantity, market conditions and other factors vary. Please call or send a quick inquiry ... Thanks!' => 'Цена на основе количества, рыночные условия и другие факторы различаются. Пожалуйста, позвоните или отправить быстрое сообщение ... Спасибо!',
  'Product Details' => 'Подробнее',
  'Products' => 'Продукты',
  'Products Show' => 'Продукты Показать',
  'Quality Control' => 'контроль качества',
  'Quantity' => 'количество',
  'Questions? Please consult our sales' => 'Вопросы? Обратите внимание на нашу продаж',
  'Service' => 'служба',
  'Technology' => 'технология',
  'Tips: Please fill in the following information to facilitate contact!' => 'Советы: Пожалуйста, заполните следующую информацию, чтобы облегчить контакт!',
);
