<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Rm. 1005, Block B,Zhonghangbeiyuan Building,Zhonghang Rd.,Futian District,Shenzhen,Guangdong,China' => '',
  'Add: Rm. 1005, Block B,Zhonghangbeiyuan Building,Zhonghang Rd.,Futian District,Shenzhen,Guangdong,China' => '@@Добавить: Rm. 1005, блок Б, Zhonghangbeiyuan Строительство, Zhonghang Rd., Futian округа, Шэньчжэнь, провинция Гуандун, Китай@@',
  'Mark is required, please fill out accurate。' => '@@Марк требуется, заполните точным.@@',
  'Sales' => '@@Реализация@@',
  'Add' => 'Добавлять',
  'All' => 'Все',
  'Any question? Please consult our technical staff and customer service personnel!' => 'Любой вопрос? Пожалуйста, обратитесь в наш технический персонал и персонал обслуживания клиента!',
  'Barum Electronics Co., LTD had been established， in line with the good faith principle, is supreme, the mutually beneficial reciprocal benefit management ' => 'Barum Электроника, Лтд была создана в соответствии с хорошей принципе веры, является высшим, взаимовыгодное обратная управления выгода',
  'Brand agency' => 'Бренд агентство',
  'Captcha' => 'Captcha',
  'Change Pic' => 'Изменить Pic',
  'Classify' => 'Классифицировать',
  'Click for Pic' => 'Нажмите для Pic',
  'Company' => 'Компания',
  'Contact' => 'Контакт',
  'Contact Us' => 'Связаться с нами',
  'Content' => 'Содержание',
  'Create Date' => 'Дата создания',
  'Customer Service' => 'Обслуживание клиентов',
  'Delete' => 'Удалять',
  'Direction' => 'Направление',
  'Fast delivery' => 'Быстрая доставка',
  'Fax' => 'Факс',
  'Headline' => 'Заголовок',
  'Honesty' => 'Честность',
  'Index' => 'Индекс',
  'Keyword' => 'Ключевое слово',
  'Large inventory spot' => 'Большой пятно инвентаризации',
  'Manufacturer' => 'Производитель',
  'Mark is required, please fill out accurate' => 'Марк требуется, заполните точным',
  'Model' => 'Модель',
  'More than 500 global components brands channels of supply and distributed components of the United States, Europe, Asia these brand manufacturers, including integrated circuits, two transistors, resistors and capacitors, connectors, modules, etc.' => 'Более 500 глобальных компоненты бренды каналов снабжения и распределенными компонентами Соединенных Штатов, Европы, Азии эти производители марки, в том числе интегральных схем, двух транзисторов, резисторов и конденсаторов, разъемы, модули и т.д.',
  'Online Inquiry' => 'Онлайн запрос',
  'Package' => 'Пакет',
  'Please enter the quantity you need. If you have more than one component are looking for, please add additional components to your quote request form. Then fill in your contact information and click on submit an application, our sales representative will contact you as soon as possible, including price and delivery time. If you need help, please send an E-MAIL to info@barum-hk.com' => 'Пожалуйста, введите необходимое Вам количество. Если у вас есть более одного компонента ищете, пожалуйста, добавить дополнительные компоненты в форму запроса котировок. Тогда заполните контактную информацию и нажмите подать заявку, наш торговый представитель свяжется с Вами как можно скорее, в том числе цены и времени доставки. Если вам нужна помощь, пожалуйста, отправьте электронное письмо по info@barum-hk.com',
  'Please select a manufacturers:' => 'Пожалуйста, выберите группу производителей:',
  'Please select a product classify:' => 'Пожалуйста, выберите КЛАССИФИЦИРОВАТЬ продукта:',
  'Price' => 'Цена',
  'Product List' => 'Список продуктов',
  'Provide one-stop service' => 'Обеспечить единый сервис',
  'Quantity' => 'Количество',
  'Quick Quote, quality' => 'Быстрый Цитата, качество',
  'Reliable' => 'Надежный',
  'Search' => 'Поиск',
  'Search Model:' => 'Поиск модели:',
  'Specialty' => 'Специальность',
  'Submit' => 'Представлять',
  'Technical Support' => 'Техническая поддержка',
  'Tel' => 'Телефон',
  'Telephone' => 'Телефон',
  'View map' => 'Показать на карте',
  'Welcome to Barum Electronics' => 'Добро пожаловать Barum электроники',
  'Why Barum?' => 'Почему Barum?',
);
