<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '63eu.com' => '',
  'Contact Person' => '',
  'Incorrect verification code' => '',
  'SendRFQ' => '',
  'Website Technology Support' => '',
  'About Us' => 'हमारे बारे में',
  'Advantage' => 'लाभ',
  'All Manufacturers' => 'सभी निर्माताओं',
  'Applications' => 'ऐप्लकेशन',
  'Barum Electronics Co., LTD' => 'Barum इलेक्ट्रॉनिक्स कं, लिमिटेड',
  'Click to learn more' => 'अधिक जानने के लिए क्लिक करें',
  'Company Events' => 'कंपनी गतिविधियाँ',
  'Contact Us' => 'हमसे संपर्क करें',
  'Culture' => 'संस्कृति',
  'Customers' => 'ग्राहक',
  'Direction' => 'दिशा',
  'Distribution Brands' => 'वितरण ब्रांड',
  'Feature' => 'फ़ीचर',
  'Help' => 'मदद',
  'Home' => 'घर',
  'Manufacturer' => 'निर्माता',
  'Manufacturers' => 'निर्माता',
  'Model' => 'मॉडल',
  'New Technologies' => 'नई प्रौद्योगिकियों',
  'Online Inquiry' => 'ऑनलाइन पूछताछ',
  'Order Tracking' => 'आदेश ट्रैकिंग',
  'Ordering Information' => 'आदेश की जानकारी',
  'Package' => 'पैकेज',
  'Popular Searches' => 'लोकप्रिय खोजों',
  'Price based on quantity, market conditions and other factors vary. Please call or send a quick inquiry ... Thanks!' => 'मात्रा के आधार पर मूल्य, बाजार की स्थिति और अन्य कारकों बदलती हैं. एक त्वरित जांच फोन या भेज ... धन्यवाद!',
  'Product Details' => 'उत्पाद विवरण',
  'Products' => 'उत्पाद',
  'Products Show' => 'उत्पाद दिखाएँ',
  'Quality Control' => 'गुणवत्ता नियंत्रण',
  'Quantity' => 'मात्रा',
  'Questions? Please consult our sales' => 'प्रश्न? हमारी बिक्री से परामर्श करें',
  'Service' => 'सेवा',
  'Technology' => 'प्रौद्योगिकी',
  'Tips: Please fill in the following information to facilitate contact!' => 'सुझाव: संपर्क की सुविधा के लिए निम्नलिखित जानकारी भरें!',
);
