<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Rm. 1005, Block B,Zhonghangbeiyuan Building,Zhonghang Rd.,Futian District,Shenzhen,Guangdong,China' => '',
  'Add: Rm. 1005, Block B,Zhonghangbeiyuan Building,Zhonghang Rd.,Futian District,Shenzhen,Guangdong,China' => '@@जोड़ें: Rm. 1005, ब्लॉक बी, Zhonghangbeiyuan बिल्डिंग, Zhonghang रोड., Futian जिला, शेन्ज़ेन, गुआंग्डोंग, चीन@@',
  'Mark is required, please fill out accurate。' => '@@मार्क आवश्यक है, सही भरें.@@',
  'Sales' => '@@विक्रय@@',
  'Add' => 'जोड़ना',
  'All' => 'सब',
  'Any question? Please consult our technical staff and customer service personnel!' => 'कोई सवाल? हमारे तकनीकी स्टाफ और ग्राहक सेवा कर्मियों से परामर्श करें!',
  'Barum Electronics Co., LTD had been established， in line with the good faith principle, is supreme, the mutually beneficial reciprocal benefit management ' => 'Barum इलेक्ट्रॉनिक्स कं, लिमिटेड अच्छा विश्वास के सिद्धांत के साथ लाइन में, स्थापित किया गया था, सर्वोच्च है, पारस्परिक रूप से लाभप्रद पारस्परिक लाभ प्रबंधन',
  'Brand agency' => 'ब्रांड एजेंसी',
  'Captcha' => 'कैप्चा',
  'Change Pic' => 'बदले तस्वीर',
  'Classify' => 'वर्गीकरण करना',
  'Click for Pic' => 'तस्वीर के लिए क्लिक करें',
  'Company' => 'कंपनी',
  'Contact' => 'संपर्क',
  'Contact Us' => 'हमसे संपर्क करें',
  'Content' => 'सामग्री',
  'Create Date' => 'तिथि बनाएँ',
  'Customer Service' => 'ग्राहक सेवा',
  'Delete' => 'हटाना',
  'Direction' => 'दिशा',
  'Fast delivery' => 'फास्ट वितरण',
  'Fax' => 'फैक्स',
  'Headline' => 'शीर्षक',
  'Honesty' => 'ईमानदारी',
  'Index' => 'अनुक्रमणिका',
  'Keyword' => 'कीवर्ड',
  'Large inventory spot' => 'बड़ी सूची के स्थान',
  'Manufacturer' => 'निर्माता',
  'Mark is required, please fill out accurate' => 'मार्क आवश्यक है, सही भरें',
  'Model' => 'मॉडल',
  'More than 500 global components brands channels of supply and distributed components of the United States, Europe, Asia these brand manufacturers, including integrated circuits, two transistors, resistors and capacitors, connectors, modules, etc.' => '500 से अधिक वैश्विक घटकों की आपूर्ति और संयुक्त राज्य अमेरिका, यूरोप, एशिया की वितरित घटकों के चैनलों ब्रांडों आदि एकीकृत सर्किट, दो ट्रांजिस्टर, प्रतिरोधों और capacitors, कनेक्टर्स, मॉड्यूल, सहित इन ब्रांड निर्माताओं,',
  'Online Inquiry' => 'ऑनलाइन पूछताछ',
  'Package' => 'पैकेज',
  'Please enter the quantity you need. If you have more than one component are looking for, please add additional components to your quote request form. Then fill in your contact information and click on submit an application, our sales representative will contact you as soon as possible, including price and delivery time. If you need help, please send an E-MAIL to info@barum-hk.com' => 'आप की जरूरत मात्रा दर्ज करें. आप एक से अधिक घटक के लिए देख रहे हैं, तो अपनी बोली अनुरोध फॉर्म को अतिरिक्त घटकों को जोड़ने के लिए धन्यवाद. फिर अपने संपर्क जानकारी में भरें और एक आवेदन प्रस्तुत पर क्लिक करें, हमारे प्रतिनिधि बिक्री मूल्य और प्रसव के समय सहित, जितनी जल्दी हो सके आपसे संपर्क करेंगे. यदि आपको मदद की जरूरत है, info@barum-hk.com को एक ई मेल भेजने के लिए कृपया',
  'Please select a manufacturers:' => 'एक निर्माता का चयन करें:',
  'Please select a product classify:' => 'एक उत्पाद वर्गीकृत चयन करें:',
  'Price' => 'कीमत',
  'Product List' => 'उत्पाद सूची',
  'Provide one-stop service' => 'एक बंद सेवा प्रदान',
  'Quantity' => 'मात्रा',
  'Quick Quote, quality' => 'त्वरित बोली, गुणवत्ता',
  'Reliable' => 'विश्वसनीय',
  'Search' => 'खोज',
  'Search Model:' => 'खोज आदर्श:',
  'Specialty' => 'विशेषता',
  'Submit' => 'प्रस्तुत करना',
  'Technical Support' => 'तकनीकी समर्थन',
  'Tel' => 'दूरभाष',
  'Telephone' => 'टेलीफोन',
  'View map' => 'मानचित्र दिखायें',
  'Welcome to Barum Electronics' => 'Barum इलेक्ट्रॉनिक्स में आपका स्वागत है',
  'Why Barum?' => 'क्यों Barum?',
);
