<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
'Add: Rm. 1005, Block B,Zhonghangbeiyuan Building,Zhonghang Rd.,Futian District,Shenzhen,Guangdong,China'=> 'Add: Rm. 1005, Block B,Zhonghangbeiyuan Building,Zhonghang Rd.,Futian District,Shenzhen,Guangdong,China',
 'All'=> 'All',
 'Any question? Please consult our technical staff and customer service personnel!'=> 'Any question? Please consult our technical staff and customer service personnel!',
 'Barum Electronics Co., LTD had been established， in line with the good faith principle, is supreme, the mutually beneficial reciprocal benefit management '=> 'Barum Electronics Co., LTD had been established， in line with the good faith principle, is supreme, the mutually beneficial reciprocal benefit management ',
 'Brand agency'=> 'Brand agency',
 'Captcha'=> 'Captcha',
 'Change Pic'=> 'Change Pic',
 'Classify'=> 'Classify',
 'Click for Pic'=> 'Click for Pic',
 'Company'=> 'Company',
 'Contact'=> 'Contact',
 'Contact Us'=> 'Contact Us',
 'Content'=> 'Content',
 'Create Date'=> 'Create Date',
 'Customer Service'=> 'Customer Service',
 'Direction'=> 'Direction',
 'Fast delivery'=> 'Fast delivery',
 'Fax'=> 'Fax',
 'Headline'=> 'Headline',
 'Honesty'=> 'Honesty',
 'Index'=> 'Index',
 'Keyword'=> 'Keyword',
 'Large inventory spot'=> 'Large inventory spot',
 'Model'=> 'Model',
 'More than 500 global components brands channels of supply and distributed components of the United States, Europe, Asia these brand manufacturers, including integrated circuits, two transistors, resistors and capacitors, connectors, modules, etc.'=> 'More than 500 global components brands channels of supply and distributed components of the United States, Europe, Asia these brand manufacturers, including integrated circuits, two transistors, resistors and capacitors, connectors, modules, etc.',
 'Online Inquiry'=> 'Online Inquiry',
 'Package'=> 'Package',
 'Please select a manufacturers:'=> 'Please select a manufacturers:',
 'Please select a product classify:'=> 'Please select a product classify:',
 'Price'=> 'Price',
 'Product List'=> 'Product List',
 'Provide one-stop service'=> 'Provide one-stop service',
 'Quantity'=> 'Quantity',
 'Quick Quote, quality'=> 'Quick Quote, quality',
 'Reliable'=> 'Reliable',
 'Sales'=> 'Sales',
 'Search'=> 'Search',
 'Search Model:'=> 'Search Model:',
 'Specialty'=> 'Specialty',
 'Technical Support'=> 'Technical Support',
 'Tel'=> 'Tel',
 'Telephone'=> 'Telephone',
 'View map'=> 'View map',
 'Welcome to Barum Electronics'=> 'Welcome to Barum Electronics',
 'Why Barum?'=> 'Why Barum?',
 );
