<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '63eu.com' => '',
  'Contact Person' => '',
  'Incorrect verification code' => '',
  'SendRFQ' => '',
  'Website Technology Support' => '',
  'About Us' => 'Hakkımızda',
  'Advantage' => 'avantaj',
  'All Manufacturers' => 'Tüm Üreticiler',
  'Applications' => 'uygulamalar',
  'Barum Electronics Co., LTD' => 'Barum Electronics Co LTD',
  'Click to learn more' => 'Daha fazla bilgi için tıklayınız',
  'Company Events' => 'Şirket Olaylar',
  'Contact Us' => 'Bize Ulaşın',
  'Culture' => 'kültür',
  'Customers' => 'Müşteriler',
  'Direction' => 'yön',
  'Distribution Brands' => 'dağıtım Markalar',
  'Feature' => 'özellik',
  'Help' => 'Yardım',
  'Home' => 'ev',
  'Manufacturer' => 'üretici',
  'Manufacturers' => 'Üreticiler',
  'Model' => 'model',
  'New Technologies' => 'yeni Teknolojiler',
  'Online Inquiry' => 'Online Sorgulama',
  'Order Tracking' => 'Sipariş Takibi',
  'Ordering Information' => 'Sipariş Bilgileri',
  'Package' => 'paket',
  'Popular Searches' => 'popüler aramalar',
  'Price based on quantity, market conditions and other factors vary. Please call or send a quick inquiry ... Thanks!' => 'Miktarına göre fiyat, piyasa koşulları ve diğer faktörler çeşitlidir. Hızlı bir soruşturma aramak veya gönderin lütfen ... Teşekkürler!',
  'Product Details' => 'Ürün Detayı',
  'Products' => 'Ürünler',
  'Products Show' => 'ürünleri göster',
  'Quality Control' => 'Kalite Kontrol',
  'Quantity' => 'miktar',
  'Questions? Please consult our sales' => 'Sorular? Bizim satış danışın',
  'Service' => 'hizmet',
  'Technology' => 'teknoloji',
  'Tips: Please fill in the following information to facilitate contact!' => 'İpuçları: temasını kolaylaştırmak için aşağıdaki bilgileri doldurunuz!',
);
