<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
'Add: Rm. 1005, Block B,Zhonghangbeiyuan Building,Zhonghang Rd.,Futian District,Shenzhen,Guangdong,China'=> 'Ekle: Rm. 1005, B Blok, Zhonghangbeiyuan Binası, Zhonghang Rd., Futian District, Shenzhen, Guangdong, Çin',
 'All'=> 'Tüm',
 'Any question? Please consult our technical staff and customer service personnel!'=> 'Herhangi bir soru? Teknik personel ve müşteri hizmetleri personeli danışın!',
 'Barum Electronics Co., LTD had been established， in line with the good faith principle, is supreme, the mutually beneficial reciprocal benefit management '=> 'Barum Electronics Co LTD iyi niyet ilkesi doğrultusunda, kurulmuş olan, yüce, karşılıklı yarar karşılıklı yarar yönetimi',
 'Brand agency'=> 'Marka ajansı',
 'Captcha'=> 'Captcha',
 'Change Pic'=> 'Değişim Pic',
 'Classify'=> 'Sınıflandırmak',
 'Click for Pic'=> 'Pic için tıklayın',
 'Company'=> 'Şirket',
 'Contact'=> 'Temas',
 'Contact Us'=> 'Bize Ulaşın',
 'Content'=> 'Içerik',
 'Create Date'=> 'Üyelik Oluştur',
 'Customer Service'=> 'Müşteri Hizmetleri',
 'Direction'=> 'Yön',
 'Fast delivery'=> 'Hızlı teslimat',
 'Fax'=> 'Faks',
 'Headline'=> 'Başlık',
 'Honesty'=> 'Dürüstlük',
 'Index'=> 'Indeks',
 'Keyword'=> 'Kelime',
 'Large inventory spot'=> 'Büyük envanter nokta',
 'Model'=> 'Model',
 'More than 500 global components brands channels of supply and distributed components of the United States, Europe, Asia these brand manufacturers, including integrated circuits, two transistors, resistors and capacitors, connectors, modules, etc.'=> '500\'den fazla küresel bileşenleri arz ve Amerika Birleşik Devletleri, Avrupa, Asya dağıtılmış bileşenler kanallarını markalar vb entegre devreler, iki transistörler, dirençler ve kapasitörler, konnektörler, modüller, dahil olmak üzere bu marka üreticileri,',
 'Online Inquiry'=> 'Online Sorgulama',
 'Package'=> 'Paket',
 'Please select a manufacturers:'=> 'Bir üreticileri seçiniz:',
 'Please select a product classify:'=> 'Bir ürün sınıflandırır seçiniz:',
 'Price'=> 'Fiyat',
 'Product List'=> 'Ürün Listesi',
 'Provide one-stop service'=> 'Tek elden hizmet sunmak',
 'Quantity'=> 'Miktar',
 'Quick Quote, quality'=> 'Hızlı Alıntı kalite',
 'Reliable'=> 'Güvenilir',
 'Sales'=> 'Satış',
 'Search'=> 'Arama',
 'Search Model:'=> 'Ara Model:',
 'Specialty'=> 'Uzmanlık',
 'Technical Support'=> 'Teknik Destek',
 'Tel'=> 'Tel',
 'Telephone'=> 'Telefon',
 'View map'=> 'Haritayı',
 'Welcome to Barum Electronics'=> 'Barum Elektronik Hoşgeldiniz',
 'Why Barum?'=> 'Neden Barum?',
 );
