<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
'About Us'=> 'Qui sommes-nous',
 'Advantage'=> 'avantage',
 'All Manufacturers'=> 'tous les fabricants',
 'Applications'=> 'applications',
 'Barum Electronics Co., LTD'=> 'Barum Electronics Co., LTD',
 'Click to learn more'=> 'Cliquez pour en savoir plus',
 'Company Events'=> 'Société Événements',
 'Contact Us'=> 'Contactez-nous',
 'Culture'=> 'culture',
 'Customers'=> 'clientèle',
 'Direction'=> 'direction',
 'Distribution Brands'=> 'Marques de distribution',
 'Feature'=> 'caractéristique',
 'Help'=> 'aider',
 'Home'=> 'maison',
 'Manufacturer'=> 'fabricant',
 'Manufacturers'=> 'fabricants',
 'Model'=> 'modèle',
 'New Technologies'=> 'nouvelles Technologies',
 'Online Inquiry'=> 'enquête en ligne',
 'Order Tracking'=> 'Suivi de commande',
 'Ordering Information'=> 'Informations de commande',
 'Package'=> 'paquet',
 'Popular Searches'=> 'recherches les plus populaires',
 'Price based on quantity, market conditions and other factors vary. Please call or send a quick inquiry ... Thanks!'=> 'Prix ​​basé sur la quantité, les conditions du marché et d\'autres facteurs varient. S\'il vous plaît appelez ou envoyez une enquête rapide ... Merci!',
 'Product Details'=> 'Détails sur le produit',
 'Products'=> 'produits',
 'Products Show'=> 'Afficher les produits',
 'Quality Control'=> 'Contrôle de la qualité',
 'Quantity'=> 'quantité',
 'Questions? Please consult our sales'=> 'Questions? S\'il vous plaît consulter nos ventes',
 'Service'=> 'service',
 'Technology'=> 'technologie',
 'Tips: Please fill in the following information to facilitate contact!'=> 'Conseils: S\'il vous plaît remplir les informations suivantes pour faciliter le contact!',
 );
