<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
'Add: Rm. 1005, Block B,Zhonghangbeiyuan Building,Zhonghang Rd.,Futian District,Shenzhen,Guangdong,China'=> 'Ajouter: Rm. 1005, Bloc B, Bâtiment Zhonghangbeiyuan, Zhonghang Rd., Futian District, Shenzhen, Guangdong, Chine',
 'All'=> 'Tout',
 'Any question? Please consult our technical staff and customer service personnel!'=> 'Une question? S\'il vous plaît consulter notre personnel technique et le personnel de service à la clientèle!',
 'Barum Electronics Co., LTD had been established， in line with the good faith principle, is supreme, the mutually beneficial reciprocal benefit management '=> 'Barum Electronics Co., LTD a été créée, en ligne avec le principe de bonne foi, est suprême, la gestion des avantages réciproques mutuellement bénéfique',
 'Brand agency'=> 'agence de marque',
 'Captcha'=> 'Captcha',
 'Change Pic'=> 'Changer Pic',
 'Classify'=> 'Classer',
 'Click for Pic'=> 'Cliquez pour Pic',
 'Company'=> 'Entreprise',
 'Contact'=> 'Contacter',
 'Contact Us'=> 'Contactez-nous',
 'Content'=> 'Teneur',
 'Create Date'=> 'Créer une date',
 'Customer Service'=> 'Service à la clientèle',
 'Direction'=> 'Direction',
 'Fast delivery'=> 'Livraison rapide',
 'Fax'=> 'Fax',
 'Headline'=> 'Titre',
 'Honesty'=> 'Honnêteté',
 'Index'=> 'Index',
 'Keyword'=> 'Mot-clé',
 'Large inventory spot'=> 'Grande tache d\'inventaire',
 'Model'=> 'Modèle',
 'More than 500 global components brands channels of supply and distributed components of the United States, Europe, Asia these brand manufacturers, including integrated circuits, two transistors, resistors and capacitors, connectors, modules, etc.'=> 'Plus de 500 composants Global Brands chaînes d\'approvisionnement et de composants distribués aux États-Unis, en Europe, en Asie ces fabricants de marque, y compris les circuits intégrés, les deux transistors, résistances et condensateurs, connecteurs, modules, etc',
 'Online Inquiry'=> 'Enquête en ligne',
 'Package'=> 'Paquet',
 'Please select a manufacturers:'=> 'S\'il vous plaît sélectionner un des fabricants:',
 'Please select a product classify:'=> 'S\'il vous plaît sélectionner un classer de produits:',
 'Price'=> 'Prix',
 'Product List'=> 'Liste des produits',
 'Provide one-stop service'=> 'Offrir un service à guichet unique',
 'Quantity'=> 'Quantité',
 'Quick Quote, quality'=> 'Citation rapide, qualité',
 'Reliable'=> 'Fiable',
 'Sales'=> 'Ventes',
 'Search'=> 'Recherche',
 'Search Model:'=> 'Recherche modèle:',
 'Specialty'=> 'Spécialité',
 'Technical Support'=> 'Support technique',
 'Tel'=> 'Tel',
 'Telephone'=> 'Téléphone',
 'View map'=> 'Voir la carte',
 'Welcome to Barum Electronics'=> 'Bienvenue à Barum Electronique',
 'Why Barum?'=> 'Pourquoi Barum?',
 );
