<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Popular Searches' => '热门搜索',
  'About Us' => '关于我们',
  'Advantage' => '企业优势',
  'All Manufacturers' => '所有供应商',
  'Applications' => '应用范围',
  'Barum Electronics Co., LTD' => '佰润电子有限公司',
  'Company Events' => '公司新闻',
  'Contact Us' => '联系我们',
  'Culture' => '企业文化',
  'Customers' => '全球客户',
  'Distribution Brands' => '分销品牌',
  'Help' => '帮助',
  'Home' => '首页',
  'Manufacturers' => '供应商',
  'New Technologies' => '最新技术',
  'Order Tracking' => '订单跟踪',
  'Ordering Information' => '订单信息',
  'Products' => '产品中心',
  'Products Show' => '产品展示',
  'Quality Control' => '质量控制',
  'Service' => '客户服务',
  'Technology' => '技术中心',
);
