<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '63eu.com' => '六三铕科技',
  'Website Technology Support' => '网站技术支持',
  'About Us' => '关于我们',
  'Advantage' => '企业优势',
  'All Manufacturers' => '所有供应商',
  'Applications' => '应用范围',
  'Barum Electronics Co., LTD' => '佰润电子有限公司',
  'Click to learn more' => '点击了解更多',
  'Company Events' => '公司新闻',
  'Contact Person' => '联系人',
  'Contact Us' => '联系我们',
  'Culture' => '企业文化',
  'Customers' => '全球客户',
  'Direction' => '注释',
  'Distribution Brands' => '分销品牌',
  'Feature' => '特性',
  'Help' => '帮助',
  'Home' => '首页',
  'Incorrect verification code' => '验证码不正确',
  'Manufacturer' => '供应商',
  'Manufacturers' => '供应商',
  'Model' => '型号',
  'New Technologies' => '最新技术',
  'Online Inquiry' => '在线询价',
  'Order Tracking' => '订单跟踪',
  'Ordering Information' => '订单信息',
  'Package' => '封装',
  'Popular Searches' => '热门搜索',
  'Price based on quantity, market conditions and other factors vary. Please call or send a quick inquiry ... Thanks!' => '价格根据数量，市场条件和其他因素而有所不同。请致电或发送一个快速询价...谢谢！',
  'Product Details' => '产品详情',
  'Products' => '产品中心',
  'Products Show' => '产品展示',
  'Quality Control' => '质量控制',
  'Quantity' => '数量',
  'Questions? Please consult our sales' => '有问题? 请咨询我们的电子技术和客户服务人员',
  'SendRFQ' => '提交询价',
  'Service' => '客户服务',
  'Technology' => '技术中心',
  'Tips: Please fill in the following information to facilitate contact!' => '温馨提示: 请填写以下信息, 方便取得联系！',
);
