<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Product List' => '产品列表',
  'Add: Rm. 1005, Block B,Zhonghangbeiyuan Building,Zhonghang Rd.,Futian District,Shenzhen,Guangdong,China' => '地址：中国广东省深圳市福田区中航路中航北苑大厦B座1005室',
  'All' => '所有',
  'Any question? Please consult our technical staff and customer service personnel!' => '有问题？请咨询我们技术人员和客服服务人员！',
  'Barum Electronics Co., LTD had been established， in line with the good faith principle, is supreme, the mutually beneficial reciprocal benefit management ' => '佰润电子有限公司成立以来,本着诚信原则,至上、互利互惠的经营理念,客户,香港基地,面对澳大利亚、台湾,积极发展国内,外的广阔的市场,获得广大客户的一致信赖和好评',
  'Brand agency' => '品牌代理',
  'Classify' => '产品分类',
  'Contact Us' => '联系我们',
  'Create Date' => '创建日期',
  'Customer Service' => '客户服务',
  'Direction' => '注释',
  'Express Stock Index' => '快捷库存索引',
  'Fast delivery' => '交货迅速',
  'Fax' => '传真',
  'Headline' => '标题',
  'Honesty' => '诚信',
  'Keyword' => '关键字',
  'Large inventory spot' => '大量库存现货',
  'Model' => '型号',
  'More than 500 global components brands channels of supply and distributed components of the United States, Europe, Asia these brand manufacturers, including integrated circuits, two transistors, resistors and capacitors, connectors, modules, etc.' => '公司已建立全球500家以上元器件品牌供应的供货渠道, 经销美、欧、亚三地品牌元器件, 包括集成电路、二三极管、电阻电容、连接器、模块等。产品特点：正品原装, 紧缺货值, 品牌货广。',
  'Online Inquiry' => '在线询价',
  'Package' => '封装',
  'Please select a product classify:' => '请选择产品分类',
  'Provide one-stop service' => '提供一站式服务',
  'Quick Quote, quality' => '快速报价，质量上乘',
  'Reliable' => '可靠',
  'Sales' => '销售部',
  'Search' => '搜索',
  'Search Model:' => '搜索型号',
  'Specialty' => '专业',
  'Technical Support' => '技术支持',
  'Tel' => '电话',
  'View map' => '查看地图',
  'Welcome to Barum Electronics' => '欢迎来到佰润电子有限公司',
  'Why Barun?' => '为什么选择佰润 ?',
);
