<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Add: Rm. 1005, Block B,Zhonghangbeiyuan Building,Zhonghang Rd.,Futian District,Shenzhen,Guangdong, China ' => '',
  'All' => '',
  'Any question? Please consult our technical staff and customer service personnel!' => '',
  'Barum Electronics Co., LTD had been established， in line with the good faith principle, is supreme, the mutually beneficial reciprocal benefit management ' => '',
  'Brand agency' => '',
  'Classify' => '',
  'Contact Us' => '',
  'Create Date' => '',
  'Customer Service' => '',
  'Direction' => '',
  'Express Stock Index' => '',
  'Fast delivery' => '',
  'Fax' => '',
  'Headline' => '',
  'Honesty' => '',
  'Keyword' => '',
  'Large inventory spot' => '',
  'Model' => '',
  'More than 500 global components brands channels of supply and distributed components of the United States, Europe, Asia these brand manufacturers, including integrated circuits, two transistors, resistors and capacitors, connectors, modules, etc.' => '',
  'Online Inquiry' => '',
  'Package' => '',
  'Please select a product classify:' => '',
  'Provide one-stop service' => '',
  'Quick Quote, quality' => '',
  'Reliable' => '',
  'Sales' => '',
  'Search' => '',
  'Search Model:' => '',
  'Specialty' => '',
  'Technical Support' => '',
  'Tel' => '',
  'View map' => '',
  'Welcome to Barum Electronics' => '',
  'Why Barun?' => '',
);
