<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '63eu.com' => '',
  'Contact Person' => '',
  'Incorrect verification code' => '',
  'SendRFQ' => '',
  'Website Technology Support' => '',
  'About Us' => '¿Quiénes somos?',
  'Advantage' => 'ventaja',
  'All Manufacturers' => 'Todos los fabricantes',
  'Applications' => 'Aplicaciones',
  'Barum Electronics Co., LTD' => 'Barum Electronics Co, LTD',
  'Click to learn more' => 'Haga clic aquí para obtener más información',
  'Company Events' => 'Eventos de la empresa',
  'Contact Us' => 'contáctenos',
  'Culture' => 'cultura',
  'Customers' => 'Clientes',
  'Direction' => 'dirección',
  'Distribution Brands' => 'Marcas de Distribución',
  'Feature' => 'característica',
  'Help' => 'ayudar',
  'Home' => 'casa',
  'Manufacturer' => 'fabricante',
  'Manufacturers' => 'Fabricantes',
  'Model' => 'modelo',
  'New Technologies' => 'Nuevas Tecnologías',
  'Online Inquiry' => 'Consulta en línea',
  'Order Tracking' => 'Seguimiento de los pedidos',
  'Ordering Information' => 'Información para hacer pedidos',
  'Package' => 'paquete',
  'Popular Searches' => 'Lo más buscado',
  'Price based on quantity, market conditions and other factors vary. Please call or send a quick inquiry ... Thanks!' => 'Precio basado en la cantidad, condiciones de mercado y otros factores varían. Por favor llame o envíe una consulta rápida, ... ¡Gracias!',
  'Product Details' => 'Detalles del producto',
  'Products' => 'Productos',
  'Products Show' => 'Demostración de los productos',
  'Quality Control' => 'control de calidad',
  'Quantity' => 'cantidad',
  'Questions? Please consult our sales' => '¿Preguntas? Por favor, consulte nuestras ventas',
  'Service' => 'servicio',
  'Technology' => 'tecnología',
  'Tips: Please fill in the following information to facilitate contact!' => 'Consejos: Por favor, complete la siguiente información para facilitar el contacto!',
);
