<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
'Add: Rm. 1005, Block B,Zhonghangbeiyuan Building,Zhonghang Rd.,Futian District,Shenzhen,Guangdong,China'=> 'Añadir: Rm. 1005, Bloque B, Zhonghangbeiyuan Building, Zhonghang RD., El distrito de Futian, Shenzhen, Guangdong, China',
 'All'=> 'Todo',
 'Any question? Please consult our technical staff and customer service personnel!'=> '¿Tiene preguntas? Consulte con nuestro personal técnico y personal de servicio al cliente!',
 'Barum Electronics Co., LTD had been established， in line with the good faith principle, is supreme, the mutually beneficial reciprocal benefit management '=> 'Barum Electrónica Co., LTD se estableció, de conformidad con el principio de buena fe, es suprema, la gestión de las prestaciones recíprocas de beneficio mutuo',
 'Brand agency'=> 'Agencia de Marca',
 'Captcha'=> 'Captcha',
 'Change Pic'=> 'Cambiar Imagen',
 'Classify'=> 'Clasificar',
 'Click for Pic'=> 'Haga clic para PIC',
 'Company'=> 'Empresa',
 'Contact'=> 'Contacto',
 'Contact Us'=> 'Contáctenos',
 'Content'=> 'Contenido',
 'Create Date'=> 'Fecha de Creación',
 'Customer Service'=> 'Servicio al cliente',
 'Direction'=> 'Dirección',
 'Fast delivery'=> 'Entrega rápida',
 'Fax'=> 'Fax',
 'Headline'=> 'Titular',
 'Honesty'=> 'Honestidad',
 'Index'=> 'Índice',
 'Keyword'=> 'Palabra clave',
 'Large inventory spot'=> 'Gran mancha inventario',
 'Model'=> 'Modelo',
 'More than 500 global components brands channels of supply and distributed components of the United States, Europe, Asia these brand manufacturers, including integrated circuits, two transistors, resistors and capacitors, connectors, modules, etc.'=> 'Más de 500 componentes Marcas mundiales de los canales de la oferta y componentes distribuidos de los Estados Unidos, Europa, Asia estos fabricantes de marcas, incluidos los circuitos integrados, los dos transistores, resistencias y condensadores, conectores, módulos, etc',
 'Online Inquiry'=> 'Consulta en línea',
 'Package'=> 'Paquete',
 'Please select a manufacturers:'=> 'Por favor seleccione un fabricantes:',
 'Please select a product classify:'=> 'Por favor seleccione una classify producto:',
 'Price'=> 'Precio',
 'Product List'=> 'Lista de Productos',
 'Provide one-stop service'=> 'Brindar un servicio de ventanilla',
 'Quantity'=> 'Cantidad',
 'Quick Quote, quality'=> 'Cotización rápida, la calidad',
 'Reliable'=> 'Seguro',
 'Sales'=> 'Venta',
 'Search'=> 'Búsqueda',
 'Search Model:'=> 'Buscar Modelo:',
 'Specialty'=> 'Especialidad',
 'Technical Support'=> 'Soporte Técnico',
 'Tel'=> 'Tel.',
 'Telephone'=> 'Teléfono',
 'View map'=> 'Ver mapa',
 'Welcome to Barum Electronics'=> 'Bienvenido a Barum Electrónica',
 'Why Barum?'=> '¿Por Barum?',
 );
