<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
'About Us'=> 'Tentang Kami',
 'Advantage'=> 'keuntungan',
 'All Manufacturers'=> 'semua Produsen',
 'Applications'=> 'aplikasi',
 'Barum Electronics Co., LTD'=> 'Barum Electronics Co, LTD',
 'Click to learn more'=> 'Klik untuk mempelajari lebih lanjut',
 'Company Events'=> 'perusahaan Events',
 'Contact Us'=> 'Hubungi Kami',
 'Culture'=> 'budaya',
 'Customers'=> 'pelanggan',
 'Direction'=> 'arah',
 'Distribution Brands'=> 'Merek distribusi',
 'Feature'=> 'ciri',
 'Help'=> 'membantu',
 'Home'=> 'rumah',
 'Manufacturer'=> 'pabrikan',
 'Manufacturers'=> 'Produsen',
 'Model'=> 'model',
 'New Technologies'=> 'Teknologi Baru',
 'Online Inquiry'=> 'Permintaan online',
 'Order Tracking'=> 'Orde Pelacakan',
 'Ordering Information'=> 'Informasi Pemesanan',
 'Package'=> 'paket',
 'Popular Searches'=> 'pencarian populer',
 'Price based on quantity, market conditions and other factors vary. Please call or send a quick inquiry ... Thanks!'=> 'Harga berdasarkan kuantitas, kondisi pasar dan faktor lainnya bervariasi. Silahkan hubungi atau mengirim penyelidikan cepat ... Terima kasih!',
 'Product Details'=> 'Detail produk',
 'Products'=> 'produk',
 'Products Show'=> 'produk Tampilkan',
 'Quality Control'=> 'Quality Control',
 'Quantity'=> 'kuantitas',
 'Questions? Please consult our sales'=> 'Pertanyaan? Silakan berkonsultasi penjualan kami',
 'Service'=> 'layanan',
 'Technology'=> 'teknologi',
 'Tips: Please fill in the following information to facilitate contact!'=> 'Tips: Silahkan isi informasi berikut untuk memfasilitasi kontak!',
 );
