<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Rm. 1005, Block B,Zhonghangbeiyuan Building,Zhonghang Rd.,Futian District,Shenzhen,Guangdong,China' => '',
  'Add: Rm. 1005, Block B,Zhonghangbeiyuan Building,Zhonghang Rd.,Futian District,Shenzhen,Guangdong,China' => '@@Add: Rm. 1005, Block B, Zhonghangbeiyuan Building, Zhonghang Rd., Futian District, Shenzhen, Guangdong, China@@',
  'Mark is required, please fill out accurate。' => '@@Mark diperlukan, isilah akurat.@@',
  'Sales' => '@@Penjualan@@',
  'Add' => 'Menambahkan',
  'All' => 'Semua',
  'Any question? Please consult our technical staff and customer service personnel!' => 'Setiap pertanyaan? Silakan berkonsultasi staf teknis kami dan petugas layanan pelanggan!',
  'Barum Electronics Co., LTD had been established， in line with the good faith principle, is supreme, the mutually beneficial reciprocal benefit management ' => 'Barum Electronics Co, LTD telah didirikan, sejalan dengan prinsip itikad baik, adalah yang tertinggi, manajemen manfaat timbal balik yang saling menguntungkan',
  'Brand agency' => 'Agen merek',
  'Captcha' => 'Captcha',
  'Change Pic' => 'Ubah Pic',
  'Classify' => 'Menggolongkan',
  'Click for Pic' => 'Klik untuk Pic',
  'Company' => 'Perusahaan',
  'Contact' => 'Kontak',
  'Contact Us' => 'Hubungi Kami',
  'Content' => 'Kadar',
  'Create Date' => 'Buat Tanggal',
  'Customer Service' => 'Layanan Pelanggan',
  'Delete' => 'Hapus',
  'Direction' => 'Arah',
  'Fast delivery' => 'Pengiriman cepat',
  'Fax' => 'Fax',
  'Headline' => 'Pokok berita',
  'Honesty' => 'Kejujuran',
  'Index' => 'Indeks',
  'Keyword' => 'Keyword',
  'Large inventory spot' => 'Besar tempat persediaan',
  'Manufacturer' => 'Pabrikan',
  'Mark is required, please fill out accurate' => 'Mark diperlukan, isilah akurat',
  'Model' => 'Model',
  'More than 500 global components brands channels of supply and distributed components of the United States, Europe, Asia these brand manufacturers, including integrated circuits, two transistors, resistors and capacitors, connectors, modules, etc.' => 'Lebih dari 500 komponen global yang Merek saluran pasokan dan komponen didistribusikan di Amerika Serikat, Eropa, Asia produsen merek tersebut, termasuk sirkuit terpadu, dua transistor, resistor dan kapasitor, konektor, modul, dll',
  'Online Inquiry' => 'Permintaan online',
  'Package' => 'Paket',
  'Please enter the quantity you need. If you have more than one component are looking for, please add additional components to your quote request form. Then fill in your contact information and click on submit an application, our sales representative will contact you as soon as possible, including price and delivery time. If you need help, please send an E-MAIL to info@barum-hk.com' => 'Masukkan jumlah yang Anda butuhkan. Jika Anda memiliki lebih dari satu komponen cari, silahkan menambahkan komponen tambahan untuk formulir permintaan penawaran Anda. Lalu isi informasi kontak Anda dan klik mengajukan permohonan, perwakilan penjualan kami akan menghubungi Anda sesegera mungkin, termasuk harga dan waktu pengiriman. Jika Anda membutuhkan bantuan, silakan kirim E-MAIL ke info@barum-hk.com',
  'Please select a manufacturers:' => 'Silahkan pilih produsen:',
  'Please select a product classify:' => 'Silahkan pilih mengklasifikasikan produk:',
  'Price' => 'Harga',
  'Product List' => 'Daftar Produk',
  'Provide one-stop service' => 'Menyediakan one-stop service',
  'Quantity' => 'Kuantitas',
  'Quick Quote, quality' => 'Kutipan Cepat, kualitas',
  'Reliable' => 'Reliable',
  'Search' => 'Pencarian',
  'Search Model:' => 'Cari Model:',
  'Specialty' => 'Khusus',
  'Submit' => 'Menyerahkan',
  'Technical Support' => 'Dukungan Teknis',
  'Tel' => 'Tel',
  'Telephone' => 'Telepon',
  'View map' => 'Lihat peta',
  'Welcome to Barum Electronics' => 'Selamat Datang di Barum Electronics',
  'Why Barum?' => 'Mengapa Barum?',
);
