<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
'About Us'=> 'Chi siamo',
 'Advantage'=> 'vantaggio',
 'All Manufacturers'=> 'tutti i produttori',
 'Applications'=> 'applicazioni',
 'Barum Electronics Co., LTD'=> 'Barum Electronics Co., LTD',
 'Click to learn more'=> 'Clicca per saperne di più',
 'Company Events'=> 'Eventi Societari',
 'Contact Us'=> 'Contattaci',
 'Culture'=> 'cultura',
 'Customers'=> 'clienti',
 'Direction'=> 'direzione',
 'Distribution Brands'=> 'Marchi di distribuzione',
 'Feature'=> 'caratteristica',
 'Help'=> 'Aiuto',
 'Home'=> 'casa',
 'Manufacturer'=> 'fabbricante',
 'Manufacturers'=> 'Produttori',
 'Model'=> 'modello',
 'New Technologies'=> 'nuove Tecnologie',
 'Online Inquiry'=> 'Richiesta online',
 'Order Tracking'=> 'Controlla il tuo ordine',
 'Ordering Information'=> 'Informazioni per l\'ordinazione',
 'Package'=> 'pacchetto',
 'Popular Searches'=> 'Ricerche più frequenti',
 'Price based on quantity, market conditions and other factors vary. Please call or send a quick inquiry ... Thanks!'=> 'Prezzo basato sulla quantità, le condizioni di mercato e altri fattori vari. Si prega di chiamare o inviare un breve inchiesta ... Grazie!',
 'Product Details'=> 'Dettagli',
 'Products'=> 'prodotti',
 'Products Show'=> 'prodotti Mostra',
 'Quality Control'=> 'controllo di qualità',
 'Quantity'=> 'quantità',
 'Questions? Please consult our sales'=> 'Domande? Si prega di consultare le nostre vendite',
 'Service'=> 'servizio',
 'Technology'=> 'tecnologia',
 'Tips: Please fill in the following information to facilitate contact!'=> 'Punte: Si prega di compilare le seguenti informazioni per facilitare il contatto!',
 );
