<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
'Add'=> 'Aggiungere',
 'Delete'=> 'Cancellare',
 'Manufacturer'=> 'Fabbricante',
 'Mark is required, please fill out accurate'=> 'Mark è necessaria, si prega di compilare accurate',
 'Please enter the quantity you need. If you have more than one component are looking for, please add additional components to your quote request form. Then fill in your contact information and click on submit an application, our sales representative will contact you as soon as possible, including price and delivery time. If you need help, please send an E-MAIL to info@barum-hk.com'=> 'Si prega di inserire la quantità che avete bisogno. Se si dispone di più di un componente alla ricerca di, si prega di aggiungere componenti aggiuntivi per il modulo di richiesta preventivo. Allora compila le informazioni di contatto e cliccare su presentare una domanda, il nostro rappresentante vi contatterà al più presto, compreso il prezzo e tempo di consegna. Se hai bisogno di aiuto, si prega di inviare una E-MAIL a info@barum-hk.com',
 'Submit'=> 'Presentare',
 'Mark is required, please fill out accurate。'=> 'Mark è necessaria, si prega di compilare accurate.',
 'Add: Rm. 1005, Block B,Zhonghangbeiyuan Building,Zhonghang Rd.,Futian District,Shenzhen,Guangdong,China'=> 'Aggiungi: Rm. 1005, Blocco B, Zhonghangbeiyuan edificio, Zhonghang Rd.., Futian District, Shenzhen, Guangdong, Cina',
 'All'=> 'Tutto',
 'Any question? Please consult our technical staff and customer service personnel!'=> 'Tutta la domanda? Si prega di consultare il nostro staff tecnico e personale di servizio al cliente!',
 'Barum Electronics Co., LTD had been established， in line with the good faith principle, is supreme, the mutually beneficial reciprocal benefit management '=> 'Barum Electronics Co., LTD era stato stabilito, in linea con il principio di buona fede, è suprema, l\'reciprocamente vantaggiosa gestione beneficio reciproco',
 'Brand agency'=> 'Agenzia Marca',
 'Captcha'=> 'Captcha',
 'Change Pic'=> 'Cambia Pic',
 'Classify'=> 'Classificare',
 'Click for Pic'=> 'Clicca per Pic',
 'Company'=> 'Azienda',
 'Contact'=> 'Contatto',
 'Contact Us'=> 'Contattaci',
 'Content'=> 'Contenuto',
 'Create Date'=> 'Data di creazione',
 'Customer Service'=> 'Servizio Clienti',
 'Direction'=> 'Direzione',
 'Fast delivery'=> 'Consegna veloce',
 'Fax'=> 'Fax',
 'Headline'=> 'Titolo',
 'Honesty'=> 'Onestà',
 'Index'=> 'Indice',
 'Keyword'=> 'Parola chiave',
 'Large inventory spot'=> 'Spot grande inventario',
 'Model'=> 'Modello',
 'More than 500 global components brands channels of supply and distributed components of the United States, Europe, Asia these brand manufacturers, including integrated circuits, two transistors, resistors and capacitors, connectors, modules, etc.'=> 'Più di 500 componenti globali potrà canali di approvvigionamento e componenti distribuiti degli Stati Uniti, Europa, Asia questi produttori di marca, tra cui i circuiti integrati, due transistor, resistenze e condensatori, connettori, moduli, ecc',
 'Online Inquiry'=> 'Richiesta online',
 'Package'=> 'Pacchetto',
 'Please select a manufacturers:'=> 'Si prega di selezionare un produttori:',
 'Please select a product classify:'=> 'Seleziona un classificare prodotto:',
 'Price'=> 'Prezzo',
 'Product List'=> 'Elenco prodotti',
 'Provide one-stop service'=> 'Fornire un servizio one-stop',
 'Quantity'=> 'Quantità',
 'Quick Quote, quality'=> 'Quick Quote, qualità',
 'Reliable'=> 'Affidabile',
 'Sales'=> 'Vendite',
 'Search'=> 'Ricerca',
 'Search Model:'=> 'Cerca Modello:',
 'Specialty'=> 'Specialità',
 'Technical Support'=> 'Supporto tecnico',
 'Tel'=> 'Tel',
 'Telephone'=> 'Telefono',
 'View map'=> 'Guarda la mappa',
 'Welcome to Barum Electronics'=> 'Benvenuti al Barum Electronics',
 'Why Barum?'=> 'Perché Barum?',
 );
