<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '63eu.com' => '',
  'Contact Person' => '',
  'Incorrect verification code' => '',
  'SendRFQ' => '',
  'Website Technology Support' => '',
  'About Us' => '회사 소개',
  'Advantage' => '이점',
  'All Manufacturers' => '모든 제조업체',
  'Applications' => '응용 프로그램',
  'Barum Electronics Co., LTD' => 'Barum 전자 유한 공사',
  'Click to learn more' => '자세한 내용을 보려면 클릭하세요',
  'Company Events' => '기업 일정',
  'Contact Us' => '저희에게 연락하십시오',
  'Culture' => '문화',
  'Customers' => '고객',
  'Direction' => '방향',
  'Distribution Brands' => '유통 브랜드',
  'Feature' => '특징',
  'Help' => '도와주세요',
  'Home' => '홈',
  'Manufacturer' => '제조업 자',
  'Manufacturers' => '제조 업체',
  'Model' => '모델',
  'New Technologies' => '신기술',
  'Online Inquiry' => '온라인 문의',
  'Order Tracking' => '주문 추적',
  'Ordering Information' => '주문 정보',
  'Package' => '꾸러미',
  'Popular Searches' => '인기 검색어',
  'Price based on quantity, market conditions and other factors vary. Please call or send a quick inquiry ... Thanks!' => '수량에 따라 가격, 시장 상황 및 기타 요인에 따라 다릅니다. 빠른 문의 전화 또는 보내 주시기 바랍니다 ... 감사합니다!',
  'Product Details' => '제품 상세 정보',
  'Products' => '제품',
  'Products Show' => '제품보기',
  'Quality Control' => '품질 관리',
  'Quantity' => '양',
  'Questions? Please consult our sales' => '질문? 우리의 판매를 참조하십시오',
  'Service' => '서비스',
  'Technology' => '기술',
  'Tips: Please fill in the following information to facilitate contact!' => '팁 : 접촉을 용이하게하기 위해 다음의 정보를 입력 해주세요!',
);
