<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
'Add: Rm. 1005, Block B,Zhonghangbeiyuan Building,Zhonghang Rd.,Futian District,Shenzhen,Guangdong,China'=> '추가 : RM은. 1005 블록 B, Zhonghangbeiyuan 빌딩 Zhonghang RD., 복전 구, 심천, 광동, 중국',
 'All'=> '모든',
 'Any question? Please consult our technical staff and customer service personnel!'=> '질문? 우리의 기술 직원 및 고객 서비스 담당자에게 문의하시기 바랍니다!',
 'Barum Electronics Co., LTD had been established， in line with the good faith principle, is supreme, the mutually beneficial reciprocal benefit management '=> 'Barum 전자 유한 공사는 성실 원칙에 맞춰, 설립했다, 최고​​, 상호 이익이 상호 이익 관리',
 'Brand agency'=> '브랜드 기관',
 'Captcha'=> '보안 문자',
 'Change Pic'=> '변경 그림',
 'Classify'=> '분류',
 'Click for Pic'=> '그림을 위해 클릭',
 'Company'=> '회사',
 'Contact'=> '접촉',
 'Contact Us'=> '저희에게 연락하십시오',
 'Content'=> '만족',
 'Create Date'=> '생성 날짜',
 'Customer Service'=> '고객 서비스',
 'Direction'=> '방향',
 'Fast delivery'=> '빠른 배송',
 'Fax'=> '팩스',
 'Headline'=> '표제',
 'Honesty'=> '정직',
 'Index'=> '색인',
 'Keyword'=> '키워드',
 'Large inventory spot'=> '대형 재고 자리',
 'Model'=> '모델',
 'More than 500 global components brands channels of supply and distributed components of the United States, Europe, Asia these brand manufacturers, including integrated circuits, two transistors, resistors and capacitors, connectors, modules, etc.'=> '500 개 이상의 글로벌 부품 공급 및 미국, 유럽, 아시아의 분산 구성 요소의 채널 브랜드 등 집적 회로, 두 개의 트랜지스터, 저항과 콘덴서, 커넥터, 모듈을 포함하여 이러한 브랜드 제조업체,',
 'Online Inquiry'=> '온라인 문의',
 'Package'=> '꾸러미',
 'Please select a manufacturers:'=> '제조 업체를 선택하세요 :',
 'Please select a product classify:'=> '제품을 분류를 선택하세요 :',
 'Price'=> '가격',
 'Product List'=> '제품 목록',
 'Provide one-stop service'=> '원 스톱 서비스를 제공',
 'Quantity'=> '양',
 'Quick Quote, quality'=> '빠른 견적, 품질',
 'Reliable'=> '신뢰할 수있는',
 'Sales'=> '매상',
 'Search'=> '수색',
 'Search Model:'=> '검색 모델 :',
 'Specialty'=> '전문',
 'Technical Support'=> '기술 지원',
 'Tel'=> '전화',
 'Telephone'=> '전화',
 'View map'=> '지도보기',
 'Welcome to Barum Electronics'=> 'Barum 전자에 오신 것을 환영합니다',
 'Why Barum?'=> '왜 Barum?',
 );
