<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
'About Us'=> 'Quem Somos',
 'Advantage'=> 'vantagem',
 'All Manufacturers'=> 'todas as Marcas',
 'Applications'=> 'Aplicações',
 'Barum Electronics Co., LTD'=> 'Barum Electronics Co., LTD',
 'Click to learn more'=> 'Clique para saber mais',
 'Company Events'=> 'Eventos da empresa',
 'Contact Us'=> 'Fale Conosco',
 'Culture'=> 'cultura',
 'Customers'=> 'Clientes',
 'Direction'=> 'direção',
 'Distribution Brands'=> 'Marcas de Distribuição',
 'Feature'=> 'característica',
 'Help'=> 'ajudar',
 'Home'=> 'casa',
 'Manufacturer'=> 'fabricante',
 'Manufacturers'=> 'Fabricantes',
 'Model'=> 'modelo',
 'New Technologies'=> 'Novas Tecnologias',
 'Online Inquiry'=> 'Consulta on-line',
 'Order Tracking'=> 'Acompanhe o seu pedido',
 'Ordering Information'=> 'Informações sobre pedidos',
 'Package'=> 'pacote',
 'Popular Searches'=> 'Pesquisas Populares',
 'Price based on quantity, market conditions and other factors vary. Please call or send a quick inquiry ... Thanks!'=> 'Preço baseado em quantidade, condições de mercado e outros fatores variam. Favor ligar ou enviar um inquérito rápido ... Obrigado!',
 'Product Details'=> 'Detalhes do produto',
 'Products'=> 'produtos',
 'Products Show'=> 'produtos Show',
 'Quality Control'=> 'Controle de Qualidade',
 'Quantity'=> 'quantidade',
 'Questions? Please consult our sales'=> 'Dúvidas? Por favor, consulte as nossas vendas',
 'Service'=> 'serviço',
 'Technology'=> 'tecnologia',
 'Tips: Please fill in the following information to facilitate contact!'=> 'Dicas: Por favor, preencha as seguintes informações para facilitar o contato!',
 );
