<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
'Add'=> 'Adicionar',
 'Delete'=> 'Excluir',
 'Manufacturer'=> 'Fabricante',
 'Mark is required, please fill out accurate'=> 'Mark é necessária, por favor preencha preciso',
 'Please enter the quantity you need. If you have more than one component are looking for, please add additional components to your quote request form. Then fill in your contact information and click on submit an application, our sales representative will contact you as soon as possible, including price and delivery time. If you need help, please send an E-MAIL to sales@Barum.com'=> 'Por favor introduza a quantidade que você precisa. Se você tiver mais de um componente está procurando, por favor, adicionar componentes adicionais para o seu formulário de solicitação de cotação. Em seguida, preencha suas informações de contato e clique em apresentar um pedido, o nosso representante de vendas entrará em contato com você o mais breve possível, inclusive preço e prazo de entrega. Se você precisar de ajuda, por favor envie um e-mail para sales@Barum.com',
 'Submit'=> 'Submeter',
 'Mark is required, please fill out accurate。'=> 'Mark é necessária, por favor preencha preciso.',
 'Add: Rm. 1005, Block B,Zhonghangbeiyuan Building,Zhonghang Rd.,Futian District,Shenzhen,Guangdong,China'=> 'Adicionar: Rm. 1005, Bloco B, Edifício Zhonghangbeiyuan, Zhonghang Rd., Futian District, Shenzhen, Guangdong, China',
 'All'=> 'Tudo',
 'Any question? Please consult our technical staff and customer service personnel!'=> 'Qualquer pergunta? Por favor, consulte nossa equipe técnica e pessoal de serviço ao cliente!',
 'Barum Electronics Co., LTD had been established， in line with the good faith principle, is supreme, the mutually beneficial reciprocal benefit management '=> 'Barum Electronics Co., LTD foi estabelecida, em consonância com o princípio da boa-fé, é supremo, a gestão benefício recíproco mutuamente benéfica',
 'Brand agency'=> 'Agência Marca',
 'Captcha'=> 'Captcha',
 'Change Pic'=> 'Mudança Pic',
 'Classify'=> 'Classificar',
 'Click for Pic'=> 'Clique para Pic',
 'Company'=> 'Companhia',
 'Contact'=> 'Contato',
 'Contact Us'=> 'Fale Conosco',
 'Content'=> 'Conteúdo',
 'Create Date'=> 'Criar Data',
 'Customer Service'=> 'Atendimento ao cliente',
 'Direction'=> 'Direção',
 'Fast delivery'=> 'Entrega rápida',
 'Fax'=> 'Fax',
 'Headline'=> 'Manchete',
 'Honesty'=> 'Honestidade',
 'Index'=> 'Índice',
 'Keyword'=> 'Palavra chave',
 'Large inventory spot'=> 'Grande ponto de inventário',
 'Model'=> 'Modelo',
 'More than 500 global components brands channels of supply and distributed components of the United States, Europe, Asia these brand manufacturers, including integrated circuits, two transistors, resistors and capacitors, connectors, modules, etc.'=> 'Mais de 500 componentes globais marcas de canais de fornecimento e componentes distribuídos dos Estados Unidos, Europa, Ásia esses fabricantes de marca, incluindo circuitos integrados, dois transistores, resistores e capacitores, conectores, módulos, etc',
 'Online Inquiry'=> 'Consulta on-line',
 'Package'=> 'Pacote',
 'Please select a manufacturers:'=> 'Por favor seleccione um fabricantes:',
 'Please select a product classify:'=> 'Por favor seleccione um classificam produto:',
 'Price'=> 'Preço',
 'Product List'=> 'Lista de Produtos',
 'Provide one-stop service'=> 'Fornecer o serviço one-stop',
 'Quantity'=> 'Quantidade',
 'Quick Quote, quality'=> 'Citação rápida, a qualidade',
 'Reliable'=> 'Confiável',
 'Sales'=> 'De vendas',
 'Search'=> 'Pesquisa',
 'Search Model:'=> 'Pesquisa Modelo:',
 'Specialty'=> 'Especialidade',
 'Technical Support'=> 'Suporte Técnico',
 'Tel'=> 'Tel',
 'Telephone'=> 'Telefone',
 'View map'=> 'Ver mapa',
 'Welcome to Barum Electronics'=> 'Bem-vindo ao Barum Eletrônica',
 'Why Barum?'=> 'Por Barum?',
 );
