<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
'About Us'=> 'over ons',
 'Advantage'=> 'voordeel',
 'All Manufacturers'=> 'Alle fabrikanten',
 'Applications'=> 'toepassingen',
 'Barum Electronics Co., LTD'=> 'Barum Electronics Co, Ltd',
 'Click to learn more'=> 'Klik voor meer informatie',
 'Company Events'=> 'bedrijfsevenementen',
 'Contact Us'=> 'Contacteer ons',
 'Culture'=> 'cultuur',
 'Customers'=> 'klanten',
 'Direction'=> 'richting',
 'Distribution Brands'=> 'distributie Merken',
 'Feature'=> 'kenmerken',
 'Help'=> 'Help',
 'Home'=> 'thuis',
 'Manufacturer'=> 'fabrikant',
 'Manufacturers'=> 'fabrikanten',
 'Model'=> 'model',
 'New Technologies'=> 'nieuwe Technologieën',
 'Online Inquiry'=> 'online Inquiry',
 'Order Tracking'=> 'Om Tracking',
 'Ordering Information'=> 'Bestelinformatie',
 'Package'=> 'verpakking',
 'Popular Searches'=> 'populaire zoekopdrachten',
 'Price based on quantity, market conditions and other factors vary. Please call or send a quick inquiry ... Thanks!'=> 'Prijs op basis van de hoeveelheid, de marktomstandigheden en andere factoren variëren. Bel of stuur een snelle vraag ... Bedankt!',
 'Product Details'=> 'product Details',
 'Products'=> 'producten',
 'Products Show'=> 'producten tonen',
 'Quality Control'=> 'Quality Control',
 'Quantity'=> 'hoeveelheid',
 'Questions? Please consult our sales'=> 'Vragen? Gelieve onze verkoop raadplegen',
 'Service'=> 'service',
 'Technology'=> 'technologie',
 'Tips: Please fill in the following information to facilitate contact!'=> 'Tips: Gelieve de volgende informatie in te vullen om contact te vergemakkelijken!',
 );
