<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
'Add: Rm. 1005, Block B,Zhonghangbeiyuan Building,Zhonghang Rd.,Futian District,Shenzhen,Guangdong,China'=> 'Voeg toe: Rm. 1005, Blok B, Zhonghangbeiyuan Building, Zhonghang Rd., Futian District, Shenzhen, Guangdong, China',
 'All'=> 'Alle',
 'Any question? Please consult our technical staff and customer service personnel!'=> 'Hebt u een vraag? Raadpleeg onze technische staf en personeel van de klantenservice!',
 'Barum Electronics Co., LTD had been established， in line with the good faith principle, is supreme, the mutually beneficial reciprocal benefit management '=> 'Barum Electronics Co, Ltd werd opgericht, in overeenstemming met het beginsel van goede trouw, is verheven, de wederzijds voordelige wederzijdse beheer van de uitkeringen',
 'Brand agency'=> 'Brand agentschap',
 'Captcha'=> 'Captcha',
 'Change Pic'=> 'Change Pic',
 'Classify'=> 'Classificeren',
 'Click for Pic'=> 'Klik voor Pic',
 'Company'=> 'Vennootschap',
 'Contact'=> 'Contact',
 'Contact Us'=> 'Contacteer ons',
 'Content'=> 'Inhoud',
 'Create Date'=> 'Maak Datum',
 'Customer Service'=> 'Klantenservice',
 'Direction'=> 'Richting',
 'Fast delivery'=> 'Snelle levering',
 'Fax'=> 'Fax',
 'Headline'=> 'Opschrift',
 'Honesty'=> 'Eerlijkheid',
 'Index'=> 'Index',
 'Keyword'=> 'Trefwoord',
 'Large inventory spot'=> 'Grote voorraad spot',
 'Model'=> 'Model',
 'More than 500 global components brands channels of supply and distributed components of the United States, Europe, Asia these brand manufacturers, including integrated circuits, two transistors, resistors and capacitors, connectors, modules, etc.'=> 'Meer dan 500 wereldwijde merken onderdelen kanalen van het aanbod en gedistribueerde componenten van de Verenigde Staten, Europa, Azië deze merk fabrikanten, met inbegrip van geïntegreerde schakelingen, twee transistoren, weerstanden en condensatoren, connectoren, modules, etc.',
 'Online Inquiry'=> 'Online Inquiry',
 'Package'=> 'Verpakking',
 'Please select a manufacturers:'=> 'Selecteer een fabrikant:',
 'Please select a product classify:'=> 'Selecteer een product in te delen:',
 'Price'=> 'Prijs',
 'Product List'=> 'Catalogus',
 'Provide one-stop service'=> 'Bieden one-stop service',
 'Quantity'=> 'Hoeveelheid',
 'Quick Quote, quality'=> 'Quick Quote, kwaliteit',
 'Reliable'=> 'Betrouwbaar',
 'Sales'=> 'Sales',
 'Search'=> 'Zoeken',
 'Search Model:'=> 'Search Model:',
 'Specialty'=> 'Specialiteit',
 'Technical Support'=> 'Technische ondersteuning',
 'Tel'=> 'Tel',
 'Telephone'=> 'Telefoon',
 'View map'=> 'Bekijk kaart',
 'Welcome to Barum Electronics'=> 'Welkom bij Barum Electronics',
 'Why Barum?'=> 'Waarom Barum?',
 );
